### ISSUE TITLE
Is it possible to implement Andriod Fingerprint API to create and sign ethereum wallet?

### ISSUE THREAD

**Issue by avirajkhare00** [uport-project/uport-android-signer#1]
## Library to support it
[Android Fingerprint API](https://developer.android.com/about/versions/marshmallow/android-6.0)

**Comment by mirceanis** [comment]
Yes,
You have to use `KeyProtection.Level.PROMPT` when creating/importing keys.
If fingerprint sensor is available and configured on the device, then the library will prompt for the fingerprint for each key interaction.
If there is no fingerprint sensor, then it defaults to using the available screen lock (PIN/pattern) configured on device.

Documentation will be updated soon to reflect this.

**Comment by mirceanis** [comment]
Hey @avirajkhare00 
Please checkout [the updated readme](https://github.com/uport-project/uport-android-signer/blob/03e12e1bc105d8d2fb7606df52521ff38fccea4a/Readme.md) and let me know if it makes things a bit easier to understand/use

**Comment by mirceanis** [comment]
Closing this as there is more documentation available now.
Feel free to open other issues if other aspects are unclear.
